require: rubocop-rails
Documentation:
  Enabled: false

Metrics/AbcSize:
# The ABC size is a calculated magnitude, so this number can be an Integer or
# a Float.
  Max: 30

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 34

Metrics/BlockLength:
  Max: 34

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/BeginEndAlignment:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/IdentityComparison:
  Enabled: true
Lint/MissingSuper:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Lint/UselessTimes:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/KeywordParametersOrder:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereNot:
  Enabled: true
Layout/IndentationStyle:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false




